//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventory()
        {
            this.MedCheckHeaders = new HashSet<MedCheckHeader>();
        }
    
        public string InventoryID { get; set; }
        public Nullable<int> SupplyID { get; set; }
        public string StaffID { get; set; }
        public Nullable<int> SupplyQuantity { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Supply Supply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheckHeader> MedCheckHeaders { get; set; }
    }
}
