//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class MedCheckItem
    {
        [DisplayName("Med Check ID")]
        public int MedCheckID { get; set; }
        [DisplayName("Item ID")]
        public int ItemID { get; set; }
        [DisplayName("Item Quantity")]
        public int Quantity { get; set; }
    
        public virtual MedCheck MedCheck { get; set; }
        public virtual Item Item { get; set; }
    }
}
