//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MedCheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedCheck()
        {
            this.MedCheckItems = new HashSet<MedCheckItem>();
        }
        [DisplayName("MedCheck ID")]
        public int MedCheckID { get; set; }
        [DisplayName("Staff")]
        public string StaffID { get; set; }
        [DisplayName("Patient")]
        public Nullable<int> PatientID { get; set; }
        [DisplayName("Date of Visit")]
        public System.DateTime DateTimeOfVisit { get; set; }
        [DisplayName("Complaint")]
        public string Complaint { get; set; }
        [DisplayName("Diagnosis")]
        public string Diagnosis { get; set; }
        [DisplayName("Treatment")]
        public string Treatment { get; set; }
        [DisplayName("Remarks")]
        public string Remarks { get; set; }
        [DisplayName("Purpose of Visit")]
        public Nullable<int> MedCheckType { get; set; }
        [DisplayName("Status")]
        public Nullable<int> MedCheckStatus { get; set; }
        public string deleted { get; set; }
        [DisplayName("Time-In")]
        public Nullable<System.DateTime> Time_in { get; set; }
        [DisplayName("Time-Out")]
        public Nullable<System.DateTime> Time_out { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheckItem> MedCheckItems { get; set; }
    }
}
