//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class MedCheck
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedCheck()
        {
            this.MedCheckItems = new HashSet<MedCheckItem>();
        }

        [DisplayName("MedCheck ID")]
        public int MedCheckID { get; set; }
        [DisplayName("Staff ID")]
        public string StaffID { get; set; }
        [DisplayName("Patient ID")]
        public Nullable<int> PatientID { get; set; }
        [DisplayName("Data of Visit")]
        public System.DateTime DateTimeOfVisit { get; set; }
        public string Complaint { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string Remarks { get; set; }
        [DisplayName("MedCheck Type")]
        public Nullable<int> MedCheckType { get; set; }
        [DisplayName("MedCheck Status")]
        public Nullable<int> MedCheckStatus { get; set; }
        [DisplayName("Deleted")]
        public string deleted { get; set; }
        [DisplayName("Time In")]
        public Nullable<System.DateTime> Time_in { get; set; }
        [DisplayName("Time Out")]
        public Nullable<System.DateTime> Time_out { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheckItem> MedCheckItems { get; set; }
    }
}
