//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCheckDetail
    {
        public string MedCheckHID { get; set; }
        public Nullable<System.DateTime> DateofVisit { get; set; }
        public Nullable<System.TimeSpan> TimeofVisit { get; set; }
        public string Complaint { get; set; }
        public string Diagnosis { get; set; }
        public string Treatment { get; set; }
        public string Remarks { get; set; }
    
        public virtual MedCheckHeader MedCheckHeader { get; set; }
    }
}
