//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCheckHeader
    {
        public string MedCheckHID { get; set; }
        public string StaffID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string InventoryID { get; set; }
        public Nullable<int> MedCheckType { get; set; }
        public Nullable<int> MedCheckStatus { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual MedCheckDetail MedCheckDetail { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
