//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCheckItem
    {
        public int MedCheckID { get; set; }
        public string ItemID { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> returned { get; set; }
    
        public virtual MedCheck MedCheck { get; set; }
        public virtual Item Item { get; set; }
    }
}
