//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.MedCheckHeaders = new HashSet<MedCheck>();
        }
        [DisplayName("Patient ID")]
        public int PatientID { get; set; }
        [DisplayName("Last Name")]
        public string PatientLast { get; set; }
        [DisplayName("First Name")]
        public string PatientFirst { get; set; }
        [DisplayName("Middle Name")]
        public string PatientMid { get; set; }
        [DisplayName("Gender")]
        public string PatientGender { get; set; }
        [DisplayName("Birth Date")]
        public Nullable<System.DateTime> PatientBDate { get; set; }
        [DisplayName("Home Address")]
        public string PatientAddrss { get; set; }
        [DisplayName("Patient Type")]
        public Nullable<int> TypeID { get; set; }
        [DisplayName("Class")]
        public Nullable<int> PatientClass { get; set; }
        [DisplayName("College")]
        public int CollegeID { get; set; }
        public string deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheck> MedCheckHeaders { get; set; }
        public virtual PatientType PatientType { get; set; }
        public virtual PCollege PCollege { get; set; }
    }
}
