//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.MedCheckHeaders = new HashSet<MedCheck>();
        }
    
        public string StaffID { get; set; }
        [DisplayName("Last Name")]
        public string StaffLast { get; set; }
        [DisplayName("First Name")]
        public string StaffFirst { get; set; }
        [DisplayName("Middle Name")]
        public string StaffMid { get; set; }
        [DisplayName("Gender")]
        public string StaffGender { get; set; }
        [DisplayName("Password")]
        public string StaffPassword { get; set; }
        [DisplayName("Joined Date")]
        public Nullable<System.DateTime> StaffJoinedDate { get; set; }
        public Nullable<int> UserTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedCheck> MedCheckHeaders { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
