//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Supply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supply()
        {
            this.SupplyChanges = new HashSet<SupplyChanges>();
        }

        [DisplayName("Supply ID")]
        public int SupplyID { get; set; }
        [DisplayName("Item ID")]
        public string ItemID { get; set; }
        [DisplayName("Quantity")]
        public short SupplyQuantity { get; set; }
        [DisplayName("Received Date")]
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        [DisplayName("Expiration Date")]
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        [DisplayName("Removed")]
        public int removed { get; set; }
    
        public virtual Item Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyChanges> SupplyChanges { get; set; }
    }
}
