//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class SupplyChanges
    {
        public int Id { get; set; }
        [DisplayName("Supply ID")]
        public int SupplyID { get; set; }
        public System.DateTime DateChange { get; set; }
        [DisplayName("Reason of Change")]
        public string ChangeReason { get; set; }
    
        public virtual Supply Supply { get; set; }
    }
}
