//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clinic_management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply
    {
        public int SupplyID { get; set; }
        public int ItemID { get; set; }
        public string SupplyQuantity { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public string ExpirationDate { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
